service: envoys-backend

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs8.10

functions:
  index:
    cljs: envoys-backend.core/index
    events:
      - http:
          path: /
          method: get
  about:
    cljs: envoys-backend.core/about
    events:
      - http:
          path: /about
          method: get
  blog:
    cljs: envoys-backend.core/blog
    events:
      - http:
          path: /blog
          method: get
  contact:
    cljs: envoys-backend.core/contact
    events:
      - http:
          path: /contact
          method: get

plugins:
  - serverless-cljs-plugin
#  - serverless-offline

custom:
  cljsCompiler:
    lumo:
      index: true
